### ISSUE TITLE
Shulker Issue

### ISSUE THREAD

**Issue by BixPettus** [Nic4Las/Minecraft-Enderite-Mod#112]
[10:40:57] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: 'net.minecraft.world.level.block.state.BlockBehaviour$Properties net.minecraft.world.level.block.state.BlockBehaviour$Properties.m_60926_(net.minecraft.world.level.block.state.BlockBehaviour)'
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener@39ea0515 handleEvent(Lnet/minecraftforge/registries/RegisterEvent;)V
                2: LOWEST
                3: ASM: dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener@39ea0515 handleEventPost(Lnet/minecraftforge/registries/RegisterEvent;)V
java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockBehaviour$Properties net.minecraft.world.level.block.state.BlockBehaviour$Properties.m_60926_(net.minecraft.world.level.block.state.BlockBehaviour)'
        at TRANSFORMER/enderitemod@1.5.1/net.enderitemc.enderitemod.shulker.EnderiteShulkerBoxBlock.<init>(EnderiteShulkerBoxBlock.java:42)
        at TRANSFORMER/enderitemod@1.5.1/net.enderitemc.enderitemod.EnderiteMod.lambda$static$24(EnderiteMod.java:189)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$Data.lambda$registerForForge$0(RegistrarManagerImpl.java:72)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.lambda$registerFor$0(RegistrarManagerImpl.java:198)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:76)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.registerFor(RegistrarManagerImpl.java:193)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.handleEvent(RegistrarManagerImpl.java:187)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.__EventListener_handleEvent_RegisterEvent.invoke(.dynamic)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:58)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:300)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:281)
        at LAYER PLUGIN/net.minecraftforge.javafmlmod@1.20.4-49.0.50/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:347)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:345)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:338)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:334)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:219)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:211)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:211)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:185)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.Main.main(Main.java:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91)
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:114)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
        at net.minecraftforge.bootstrap@2.1.0/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97)

[10:40:57] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegisterEvent dispatch for modid enderitemod
java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockBehaviour$Properties net.minecraft.world.level.block.state.BlockBehaviour$Properties.m_60926_(net.minecraft.world.level.block.state.BlockBehaviour)'
        at net.enderitemc.enderitemod.shulker.EnderiteShulkerBoxBlock.<init>(EnderiteShulkerBoxBlock.java:42) ~[enderitemod-1.5.1-1.20.2-forge.jar!/:?] {re:classloading}
        at net.enderitemc.enderitemod.EnderiteMod.lambda$static$24(EnderiteMod.java:189) ~[enderitemod-1.5.1-1.20.2-forge.jar!/:?] {re:mixin,re:classloading}
        at dev.architectury.registry.registries.forge.RegistrarManagerImpl$Data.lambda$registerForForge$0(RegistrarManagerImpl.java:72) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading}
        at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.lambda$registerFor$0(RegistrarManagerImpl.java:198) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading}
        at net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:76) ~[forge-1.20.4-49.0.50-universal.jar!/:?] {re:classloading,pl:eventbus:A}
        at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.registerFor(RegistrarManagerImpl.java:193) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading}
        at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.handleEvent(RegistrarManagerImpl.java:187) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading}
        at dev.architectury.registry.registries.forge.__EventListener_handleEvent_RegisterEvent.invoke(.dynamic) ~[architectury-11.1.17-minecraftforge.jar!/:?] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:58) ~[eventbus-6.2.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:300) ~[eventbus-6.2.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:281) ~[eventbus-6.2.0.jar:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.20.4-49.0.50.jar:49.0.50] {}
        at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:347) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:345) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:338) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:334) ~[forge-1.20.4-49.0.50-universal.jar:?] {re:classloading}
        at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.4-49.0.50-universal.jar:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:219) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:211) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:211) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:185) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.20.4-49.0.50.jar:1.0] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.4-49.0.50-universal.jar:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:121) ~[forge-1.20.4-49.0.50-server.jar:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.0.50.jar:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.0.50.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?] {}
        at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) ~[bootstrap-2.1.0.jar!/:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) ~[bootstrap-2.1.0.jar!/:?] {}
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) ~[bootstrap-2.1.0.jar!/:?] {}
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) ~[bootstrap-2.1.0.jar!/:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97) ~[forge-1.20.4-49.0.50-shim.jar!/:2.1.0] {}
[10:40:57] [main/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Registry Object not present: enderitemod:enderite_shulker_box
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener@39ea0515 handleEvent(Lnet/minecraftforge/registries/RegisterEvent;)V
                2: LOWEST
                3: ASM: dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener@39ea0515 handleEventPost(Lnet/minecraftforge/registries/RegisterEvent;)V
java.lang.NullPointerException: Registry Object not present: enderitemod:enderite_shulker_box
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.DeferredRegister$Entry.get(DeferredRegister.java:144)
        at TRANSFORMER/enderitemod@1.5.1/net.enderitemc.enderitemod.EnderiteMod.lambda$static$25(EnderiteMod.java:191)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$Data.lambda$registerForForge$0(RegistrarManagerImpl.java:72)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.lambda$registerFor$0(RegistrarManagerImpl.java:198)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:76)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.registerFor(RegistrarManagerImpl.java:193)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl$EventListener.handleEvent(RegistrarManagerImpl.java:187)
        at TRANSFORMER/architectury@11.1.17/dev.architectury.registry.registries.forge.__EventListener_handleEvent_RegisterEvent.invoke(.dynamic)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:58)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:300)
        at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:281)
        at LAYER PLUGIN/net.minecraftforge.javafmlmod@1.20.4-49.0.50/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:347)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:345)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:338)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:334)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:219)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:211)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:211)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:185)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at LAYER PLUGIN/net.minecraftforge.fmlcore@1.20.4-49.0.50/net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185)
        at TRANSFORMER/forge@49.0.50/net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30)
        at TRANSFORMER/minecraft@1.20.4/net.minecraft.server.Main.main(Main.java:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91)
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:114)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
        at net.minecraftforge.bootstrap@2.1.0/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.bootstrap.shim.Main.main(Main.java:97)

**Comment by Pitti11** [comment]
It seems you are trying to load enderitemod-1.5.1-1.20.2-forge with an minecraft@1.20.4 game. Forge 1.20.4 had many problems in development, so we decided to switch to NeoForge.
Please try using the correct version and modloader combinations.
