### ISSUE TITLE
java.lang.NullPointerException with EnderiteShulkerBoxRecipe in version 1.16.3-0.7.0-forge-34.1.34

### ISSUE THREAD

**Issue by wech71** [Nic4Las/Minecraft-Enderite-Mod#31]
Time: 14.03.21 11:23
Description: Container click

java.lang.NullPointerException: Container click
  at net.minecraft.item.Item.func_206844_a(Item.java:343) ~[?:?] {re:classloading,re:mixin}
  at net.enderitemc.enderitemod.recipe.EnderiteShulkerBoxRecipe.matches(EnderiteShulkerBoxRecipe.java:29) ~[?:1.16.3-0.7.0-forge-34.1.34] {re:classloading}
  at net.enderitemc.enderitemod.recipe.EnderiteShulkerBoxRecipe.func_77569_a(EnderiteShulkerBoxRecipe.java:16) ~[?:1.16.3-0.7.0-forge-34.1.34] {re:classloading}
  at net.minecraft.item.crafting.IRecipeType.func_222148_a(SourceFile:30) ~[?:?] {re:classloading}
  at net.minecraft.item.crafting.RecipeManager.lambda$getRecipe$2(RecipeManager.java:82) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.item.crafting.RecipeManager$$Lambda$5062/1722141669.apply(Unknown Source) ~[?:?] {}
  at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_51] {}
  at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1633) ~[?:1.8.0_51] {}
  at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_51] {}
  at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529) ~[?:1.8.0_51] {}
  at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516) ~[?:1.8.0_51] {}
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
  at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_51] {}
  at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
  at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464) ~[?:1.8.0_51] {}
  at net.minecraft.item.crafting.RecipeManager.func_215371_a(RecipeManager.java:83) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.item.crafting.RecipeManager.func_215369_c(RecipeManager.java:105) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.inventory.container.CraftingResultSlot.func_190901_a(CraftingResultSlot.java:59) ~[?:?] {re:classloading}
  at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:292) ~[?:?] {re:classloading,re:mixin}
  at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:classloading,re:mixin}
  at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_184098_a(SourceFile:198) ~[?:?] {re:classloading}
  at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.gui.screen.inventory.InventoryScreen.func_231044_a_(SourceFile:177) ~[?:?] {re:classloading}
  at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.MouseHelper$$Lambda$4052/64614565.run(Unknown Source) ~[?:?] {}
  at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.MouseHelper$$Lambda$4051/1593987072.run(Unknown Source) ~[?:?] {}
  at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
  at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.MouseHelper$$Lambda$3595/355920448.invoke(Unknown Source) ~[?:?] {}

Lotti, [14.03.21 11:30]
at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
  at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
  at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
  at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
  at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:304) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:973) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
  at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
  at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
  at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.42.jar:34.1] {}
  at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$434/2042884127.call(Unknown Source) [forge-1.16.3-34.1.42.jar:34.1] {}
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
  at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

**Comment by Pitti11** [comment]
Should be fixed with new update (versions 0.8.0 or newer)
